image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

release-build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - zip -R build '*.js' 'manifest.json' 'src/*' 'assets/*'
    - mv build.zip de.pabloklaschka.xdplugins.lorem.xdx
  artifacts:
    name: "lorem_$CI_COMMIT_REF_NAME.xdx"
    paths:
      - de.pabloklaschka.xdplugins.lorem.xdx
  only:
    - tags