image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

release-build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - ls
    - ls assets
    - zip -R build '*.js' 'manifest.json' 'src/*' 'assets/*' '*.png'
    - mv build.zip lorem_$CI_COMMIT_TAG.xdx
  artifacts:
    name: "lorem_$CI_COMMIT_TAG.xdx"
    paths:
      - lorem_$CI_COMMIT_TAG.xdx
  only:
    - tags