image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - zip -R build '*.js' 'manifest.json' 'src/*'
  artifacts:
    paths:
      - build.zip